---
- name: Install kubectl on Ubuntu VMs
  hosts: ubuntu_vms # Make sure this matches the group name in your inventory file
  become: yes

  tasks:
    - name: Fetch latest kubectl version
      uri:
        url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
        return_content: yes
      register: kubectl_version

    - name: Download kubectl binary
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: "0755"

    - name: Add kubectl completion
      shell: "kubectl completion bash > /etc/bash_completion.d/kubectl"
      args:
        warn: no
